spring.application.name=baking-app

# debug = true

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

spring.h2.console.enabled=true
#auto_server = true allows file based database to be accessed by multiple jvm instances
spring.datasource.url=jdbc:h2:file:C:/Users/wcheong/OneDrive - Capgemini/Desktop/baking app/database/baking-app;AUTO_SERVER=true 
spring.datasource.username=
spring.datasource.password=
# specifies jdbc driver class Spring Boot should use to connect to H2 database
# If not specified, Spring Boot will try to guess the driver class based on the URL - auto-detection
spring.datasource.driver-class-name=org.h2.Driver
# controls when Spring Boot runs SQL scripts to initialize the database
# embedded means the scripts will only run if the database is embedded (like H2)
# other options are always, never, and embedded+never
# always means the scripts will run regardless of the database type
# never means the scripts will not run at all
# embedded+never means the scripts will run only if the database is embedded, but not if it is not
spring.sql.init.mode=always
spring.sql.init.schema-locations=optional:classpath:sql/schema.sql
spring.sql.init.data-locations=optional:classpath:sql/data.sql
#Based on dependency in pom Spring data can know what type of database it's connecting to
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# generate the database schema automatically based on the entity classes
# update means that the schema will be updated automatically if it changes
# create-drop means that the schema will be created when the application starts and dropped when it stops
# create means that the schema will be created when the application starts, but not dropped when it stops
# validate means that the schema will be validated against the entity classes, but not created or updated
# none means that no schema generation will be done
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

