-- Dummy data for blog_post table
-- Spring Boot will execute this on application startup (spring.sql.init.data-locations)

INSERT INTO blog_post (title, content, author, created_at, image_url) VALUES
('Welcome to Baking App',
 'This is a sample blog post used to populate the in-memory H2 database for local testing and containerization experiments.',
 'System', CURRENT_TIMESTAMP, '/uploads/1a17467f-b8e7-48d1-b59a-f82a0788c965_BlackSesameCake.jpg'),
('How to Make Black Sesame Cake',
 'Ingredients: black sesame, flour, eggs...\nSteps: Preheat oven, mix, bake.',
 'Chef Amy', CURRENT_TIMESTAMP, '/uploads/1a17467f-b8e7-48d1-b59a-f82a0788c965_BlackSesameCake.jpg'),
('Ubeee - My Favourite Flavor',
 'A short post about the delicious ube flavour and how it inspired this demo.',
 'Foodie', CURRENT_TIMESTAMP, '/uploads/c866b897-216d-4eb7-92a3-221eddda1b53_ubeee.jpg'),
('Chocolate Chip Cookies',
 'Classic cookies with gooey chocolate chips. Perfect for any occasion.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Lemon Drizzle Cake',
 'A zesty lemon cake with a sweet drizzle topping.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Banana Bread',
 'Moist banana bread with walnuts and a hint of cinnamon.',
 'System', CURRENT_TIMESTAMP, NULL),
('Sourdough Starter Tips',
 'How to keep your sourdough starter healthy and active.',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Perfect Croissants',
 'Step-by-step guide to flaky, buttery croissants.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Vegan Brownies',
 'Rich, fudgy brownies made without eggs or dairy.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Gluten-Free Pancakes',
 'Fluffy pancakes for gluten-sensitive bakers.',
 'System', CURRENT_TIMESTAMP, NULL),
('Raspberry Tart',
 'A sweet tart with fresh raspberries and almond cream.',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Matcha Swiss Roll',
 'Light sponge cake rolled with matcha cream.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Pumpkin Pie',
 'A fall favorite with spiced pumpkin filling.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Carrot Cake',
 'Moist carrot cake with cream cheese frosting.',
 'System', CURRENT_TIMESTAMP, NULL),
('Blueberry Muffins',
 'Bursting with blueberries and a crumbly top.',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Cinnamon Rolls',
 'Soft rolls with cinnamon sugar and vanilla glaze.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Peanut Butter Cookies',
 'Chewy cookies with a rich peanut butter flavor.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Red Velvet Cupcakes',
 'Classic red velvet with cream cheese frosting.',
 'System', CURRENT_TIMESTAMP, NULL),
('Apple Crumble',
 'Warm apples with a crunchy oat topping.',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Strawberry Shortcake',
 'Layers of shortcake, cream, and strawberries.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Coffee Walnut Loaf',
 'A loaf cake with coffee and crunchy walnuts.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Orange Madeleines',
 'French madeleines with a hint of orange zest.',
 'System', CURRENT_TIMESTAMP, NULL),
('Pistachio Macarons',
 'Delicate macarons with pistachio filling.',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Classic Victoria Sponge',
 'A British classic with jam and cream.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Chocolate Lava Cake',
 'Molten chocolate center in every bite.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Honey Almond Granola Bars',
 'Homemade granola bars with honey and almonds.',
 'System', CURRENT_TIMESTAMP, NULL),
('Lime Cheesecake',
 'Creamy cheesecake with a tangy lime twist.',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Salted Caramel Brownies',
 'Brownies with gooey salted caramel swirls.',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Mango Mousse',
 'Light and airy mango mousse dessert.',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Hazelnut Biscotti',
 'Crunchy biscotti with roasted hazelnuts.',
 'System', CURRENT_TIMESTAMP, NULL);
