-- Dummy data for blog_post table
-- Spring Boot will execute this on application startup (spring.sql.init.data-locations)

INSERT INTO blog_post (title, content, author, created_at, image_url) VALUES
('Welcome to Baking App 🍰',
 'This celebratory kick-off entry explains how to navigate the Baking App demo, schedule posts, and attach festive images. Whether you are testing locally or inside a container, our seed data keeps the dashboard lively, so explore freely and leave crumb trails of feedback! 🍰',
 'System', CURRENT_TIMESTAMP, NULL),
('How to Make Black Sesame Cake 🌑',
 'From toasting sesame seeds until aromatic to whisking glossy egg whites, this walkthrough gives timing cues, oven temperature reminders, and plating inspiration so your cake slices look like lunar crescents. Finish with a tahini drizzle for extra drama. 🌑',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Ubeee - My Favourite Flavor 💜',
 'Ube jam, coconut milk, and velvety chiffon swirl together for a purple cloud that brightens any feed. Try topping with toasted coconut chips for crunch and a final dusting of powdered sugar. 💜',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Chocolate Chip Cookies 🍪',
 'This upgraded classic chills the dough overnight, browns the butter for nutty depth, and folds in two chocolate percentages so every bite swings between melty puddles and crisp edges while still staying chewy in the middle. One batch rarely lasts an afternoon. 🍪',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Lemon Drizzle Cake 🍋',
 'Mix zest directly into sugar to release citrus oils, then pour the shimmering drizzle while the loaf is hot so it soaks in like sunshine. A scattering of candied peel makes it sparkle on the table. 🍋',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Banana Bread 🍌',
 'Overripe bananas plus tangy yogurt keep this bread plush for days. Scatter walnut praline on top for a caramel crunch surprise, then toast slices for breakfast with a swipe of salted butter. 🍌',
 'System', CURRENT_TIMESTAMP, NULL),
('Sourdough Starter Tips 🥖',
 'Keep your starter in a clear jar, note the rise time after each feeding, and alternate between whole wheat and bread flour to keep the microbes enthusiastic. This logbook-style habit makes troubleshooting easy when humidity shifts season to season. 🥖',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Perfect Croissants 🥐',
 'Laminate butter that stays at fifty-five degrees, perform four single turns, and rest the dough overnight so the gluten relaxes. On baking day, proof the crescents until they wobble like custard, brush with salted egg wash, and enjoy shattery flakes. 🥐',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Vegan Brownies 🌱',
 'Aquafaba whipped into glossy peaks replaces eggs, while tahini swirls add fudginess without dairy. Sprinkle smoked salt for contrast and bake until the top crinkles. 🌱',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Gluten-Free Pancakes 🌾🚫',
 'A duo of oat flour and almond flour keeps these pancakes tender, while psyllium husk adds the stretch you normally miss in gluten-free batters. Let the batter rest, then griddle in coconut oil for caramelized edges and drizzle maple butter on top. 🫓',
 'System', CURRENT_TIMESTAMP, NULL),
('Raspberry Tart ❤️',
 'Blind-bake the almond crust, fill with silky vanilla custard, then crown with rows of raspberries and a whisper of rosewater glaze for patisserie vibes. ❤️',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Matcha Swiss Roll 🍵',
 'Whisk ceremonial-grade matcha into the sponge for color, bake thin, then spread whipped yuzu cream before rolling. Chill the log to set the spirals, dust with more matcha, and slice to reveal hypnotic swirls that wake up afternoon tea. 🍵',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Pumpkin Pie 🎃',
 'Brown the butter before mixing with pumpkin puree for a toasty aroma, then bake until the center jiggles slightly. A maple whipped cream swirl seals the deal. 🎃',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Carrot Cake 🥕',
 'This version folds in pineapple juice for moisture, toasted coconut for chew, and a citrusy cream cheese frosting that stays silky even after chilling. Decorate with pressed edible flowers so the classic sheet cake suddenly feels celebration-ready. 🥕',
 'System', CURRENT_TIMESTAMP, NULL),
('Blueberry Muffins 🔵',
 'Toss the berries with lemon zest and a pinch of cardamom, then fold into thick batter for bakery-height domes. Sparkling sugar completes the crunch. 🔵',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Cinnamon Rolls 🤎',
 'Use tangzhong starter for fluffy dough, spread with brown sugar cinnamon paste, and add a ribbon of espresso caramel before rolling up. After baking, glaze with cream cheese icing while still warm so it drips dramatically down the swirls. 🤎',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Peanut Butter Cookies 🥜',
 'Crosshatch the tops with a fork, sprinkle flaky salt, and bake until edges set but centers stay soft. Mini chocolate chunks optional but encouraged. 🥜',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Red Velvet Cupcakes ❤️',
 'Beet purée boosts color naturally, while buttermilk keeps the crumb tender. Fill each cupcake with strawberry jam, pipe tall spirals of mascarpone frosting, and shower with ruby sanding sugar for extra sparkle on dessert displays. ❤️',
 'System', CURRENT_TIMESTAMP, NULL),
('Apple Crumble 🍎',
 'Honeycrisp slices meet oat streusel spiked with cinnamon and ginger. Bake until juices bubble over the sides and serve with cinnamon ice cream. 🍎',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Strawberry Shortcake 🍓',
 'Bake flaky drop biscuits, macerate berries with balsamic and basil, and fold mascarpone into the whipped cream for tang. Stacking individual shortcakes tableside adds theatrical flair for picnics and showers alike. 🍓',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Coffee Walnut Loaf ☕️',
 'Instant espresso granules dissolved in hot milk perfume the batter, while toasted walnuts provide crunch. Finish with a shiny espresso glaze. ☕️',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Orange Madeleines 🍊',
 'Rest the batter overnight so the signature humps form, then zest two whole oranges directly into melted butter. Dip the baked shells in dark chocolate and sprinkle crushed pistachios for a tea-time cookie that feels couture. 🍊',
 'System', CURRENT_TIMESTAMP, NULL),
('Pistachio Macarons 💚',
 'Age egg whites for stable meringue, tint with pistachio paste, and sandwich around rosewater buttercream for a floral crunch. 💚',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Classic Victoria Sponge 👑',
 'Cream the butter and sugar longer than you think for pillowy texture, bake in two pans, then sandwich with strawberry jam, vanilla bean whipped cream, and a veil of caster sugar. Serve on vintage china for full tea-party drama. 👑',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Chocolate Lava Cake 🌋',
 'Underbake just enough that the center stays fluid, then serve immediately with espresso whipped cream for contrast. 🌋',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Honey Almond Granola Bars 🍯',
 'Toast oats and almonds until fragrant, bind with warm honey, peanut butter, and brown rice syrup, then press with dried cherries before chilling. Wrap individual bars in parchment so they are grab-and-go energy treats after long baking sessions. 🍯',
 'System', CURRENT_TIMESTAMP, NULL),
('Lime Cheesecake 💚🍋',
 'Blend cream cheese with lime zest, condensed milk, and a splash of tequila for a playful twist. Set over a coconut cookie crust. 💚🍋',
 'Foodie', CURRENT_TIMESTAMP, NULL),
('Salted Caramel Brownies 🧂🍫',
 'Swirl homemade caramel between layers of brownie batter, sprinkle flaky salt before and after baking, and chill before slicing for clean layers. The contrast of deep cocoa and toasty sugar makes them impossible to resist. 🧂🍫',
 'Baker Bob', CURRENT_TIMESTAMP, NULL),
('Mango Mousse 🥭',
 'Whip coconut cream, fold in mango purée, and chill in coupe glasses. Top with lemongrass syrup and toasted coconut chips. 🥭',
 'Chef Amy', CURRENT_TIMESTAMP, NULL),
('Hazelnut Biscotti 🌰',
 'Roast hazelnuts until skins slip off, fold into orange-scented dough, and double-bake for perfect crunch. Dip one end in dark chocolate and sprinkle crushed cacao nibs for a café-worthy finish that begs to be dunked. 🌰',
 'System', CURRENT_TIMESTAMP, NULL);
